{
  "type": "record",
  "name": "OrderStatusChanged",
  "namespace": "com.stoliar.events.order",
  "fields": [
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "status",
      "type": {
        "type": "enum",
        "name": "OrderStatus",
        "symbols": [
          "NEW",
          "RESERVED",
          "PAID",
          "SHIPPED",
          "COMPLETED",
          "CANCELLED"
        ]
      }
    },
    {
      "name": "changedAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}